"""add vote table

Revision ID: 6a1464c705af
Revises: 4eff32329f3c
Create Date: 2026-07-10 01:30:14.765982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1464c705af'
down_revision: Union[str, Sequence[str], None] = '4eff32329f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.Id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_index(op.f('ix_posts_Id'), 'posts', ['Id'], unique=False)
    op.create_index(op.f('ix_users_Id'), 'users', ['Id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_Id'), table_name='users')
    op.drop_index(op.f('ix_posts_Id'), table_name='posts')
    op.drop_table('votes')
    # ### end Alembic commands ###
