"""Penes column

Revision ID: 7042b0c7fc78
Revises: 6a1464c705af
Create Date: 2026-07-10 01:40:42.842610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7042b0c7fc78'
down_revision: Union[str, Sequence[str], None] = '6a1464c705af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('penes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'penes')
    # ### end Alembic commands ###
